### PR TITLE
fix #87 clean up checkpoint once sandbox non-exist

### LINKED ISSUE #87: Clean up sandbox checkpoint and network plugin properly
Currently, sandbox checkpoint is only removed after the pod is deleted successfully. However, if the hyper pod has already been removed outside, the checkpoint will be left over and kubelet will always fail on stopping sandbox.

We should ensure checkpoint and network plugin are cleaned up properly once frakti has detected the sandbox has already been non-exist.

### PR DESCRIPTION
**Pull request by heartlock**
fix #87

### CODE REVIEW

File: pkg/hyper/sandbox.go [hunk 1]
```diff
@@ -216,7 +219,6 @@ func (h *Runtime) DeletePodSandbox(podSandboxID string) error {
 
 	if err := h.checkpointHandler.RemoveCheckpoint(podSandboxID); err != nil {
 		glog.Errorf("Remove checkpoint of pod %s failed: %v", podSandboxID, err)
-		return err
```
Comment (feiskyer) [inline pkg/hyper/sandbox.go]: why removed this ?

File: pkg/hyper/sandbox.go [hunk 2]
```diff
@@ -190,7 +190,10 @@ func (h *Runtime) StopPodSandbox(podSandboxID string) error {
 	code, cause, err := h.client.StopPod(podSandboxID)
 	if err != nil {
 		glog.Errorf("Stop pod %s failed, code: %d, cause: %s, error: %v", podSandboxID, code, cause, err)
-		return err
+		err = h.checkpointHandler.RemoveCheckpoint(podSandboxID)
```
Comment (feiskyer) [inline pkg/hyper/sandbox.go]: should check error message and only remove checkpoint when pod has already been removed.

Also network plugin should be cleaned up before removing checkpoint.

File: pkg/hyper/sandbox.go (hunk 1 above)
Comment (feiskyer) [inline pkg/hyper/sandbox.go]: I think RemoveCheckpoint  should return nil if the checkpoint doesn't exist,
