### PR TITLE
Fix log-dir and create path

### LINKED ISSUE #106: Redundant flags because of introducing dockershim
There are many redundant flags because of introducing dockershim. We should clean them up.

```
      --storage-driver-buffer-duration duration   Writes in the storage driver will be buffered for this duration, and committed to the non memory backends as a single transaction (default 1m0s)
      --storage-driver-db string                  database name (default "cadvisor")
      --storage-driver-host string                database host:port (default "localhost:8086")
      --storage-driver-password string            database password (default "root")
      --storage-driver-secure                     use secure connection with database
      --storage-driver-table string               table name (default "stats")
      --storage-driver-user string                database username (default "root")
```

### PR DESCRIPTION
**Pull request by resouer**
Fixes #106 #97 

I copied `flags.go` out of vendor because we can only call `Hidden` before `Parse()`. So we have to modify `flags.go`.

### CODE REVIEW

File: pkg/util/flags/flags.go [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+
+	for _, hiddenFlag := range hiddenVendorFlags {
+		pflag.CommandLine.MarkHidden(hiddenFlag)
+	}
+
+	pflag.Parse()
+
+	path := pflag.Lookup("log-dir").Value.String()
+	if _, err := os.Stat(path); os.IsNotExist(err) {
+		os.Mkdir(path, 644)
```
Comment (feiskyer) [inline pkg/util/flags/flags.go]: should be `os.MkdirAll(path, 0755)`
